const fs = require('fs');

const content = fs.readFileSync('src/data/wordList.ts', 'utf8');
const match = content.match(/const WORD_DATA = `([\s\S]*?)`/);
const existing = new Set(match[1].split('\n').map(w => w.trim()).filter(w => w.length >= 3));
const exportSection = content.substring(content.indexOf('`;') + 2);
console.log('Starting count:', existing.size);

// Generate a big batch of common words that are likely missing
const candidates = [
// 3-letter additions
"ABS","ACE","ADD","ADO","ADS","AFT","AGA","AHA","AID","AIM","AIN","AIT","ALE","ALP","AMP","AND","ANE","ANI","ANT",
"APE","APT","ARC","ARB","ARE","ARF","ARK","ARM","ARS","ASH","ASP","ASS","ATE","ATT","AUK","AWE","AWL","AWN","AXE",
"AYE","AZO","BAA","BAD","BAG","BAH","BAM","BAP","BAR","BAT","BAY","BEE","BEG","BEL","BEN","BET","BIB","BID","BIG",
"BIN","BIS","BIT","BIZ","BOA","BOB","BOD","BOG","BOP","BOT","BOW","BOX","BOY","BRA","BRO","BRR","BUB","BUD","BUG",
"BUM","BUN","BUR","BUS","BUT","BUY","BYE","CAB","CAD","CAM","CAN","CAP","CAR","CAT","CAW","CEE","CHI","CIG","COB",
"COD","COG","COL","CON","COO","COP","COR","COS","COT","COW","COX","COZ","CRU","CRY","CUB","CUD","CUE","CUM","CUP",
"CUR","CUT","DAB","DAD","DAG","DAH","DAK","DAL","DAM","DAP","DAW","DAY","DEE","DEL","DEN","DEV","DEW","DEX","DEY",
"DIB","DID","DIG","DIM","DIN","DIP","DIS","DIT","DOC","DOE","DOG","DOL","DOM","DON","DOR","DOS","DOT","DOW","DRY",
"DUB","DUD","DUE","DUG","DUH","DUN","DUO","DUP","DYE","EAR","EAT","EAU","EEL","EGG","EGO","EKE","ELD","ELF","ELK",
"ELM","ELS","EME","EMU","END","ENG","EON","ERA","ERE","ERG","ERN","ERR","ESS","ETA","ETH","EVE","EWE","EYE","FAB",
"FAD","FAG","FAM","FAN","FAR","FAT","FAX","FAY","FED","FEE","FEH","FEM","FEN","FER","FEW","FEY","FEZ","FIB","FIG",
"FIN","FIR","FIT","FIX","FIZ","FLU","FLY","FOB","FOE","FOG","FON","FOP","FOR","FOU","FOX","FOY","FRO","FRY","FUG",
"FUN","FUR","GAB","GAD","GAG","GAL","GAM","GAN","GAP","GAR","GAS","GAT","GAY","GED","GEE","GEL","GEM","GET","GHI",
"GIG","GIN","GIP","GIT","GNU","GOA","GOB","GOD","GOO","GOR","GOT","GOV","GUL","GUM","GUN","GUP","GUT","GUV","GUY",
"GYM","GYP","HAD","HAG","HAH","HAJ","HAM","HAO","HAP","HAS","HAT","HAW","HAY","HEH","HEM","HEN","HEP","HER","HET",
"HEW","HEX","HEY","HID","HIM","HIN","HIP","HIS","HIT","HOB","HOD","HOE","HOG","HOP","HOT","HOW","HOY","HUB","HUE",
"HUG","HUH","HUM","HUN","HUP","HUT","ICE","ICH","ICK","ICY","IDS","ILL","IMP","INK","INN","INS","ION","IRE","IRK",
"ISM","ITS","IVY","JAB","JAG","JAM","JAR","JAW","JAY","JET","JIB","JIG","JIN","JOB","JOE","JOG","JOT","JOW","JOY",
"JUG","JUN","JUS","JUT","KAB","KAT","KAY","KEG","KEN","KEP","KEY","KID","KIN","KIP","KIR","KIT","KOA","KOB","KOI",
"LAB","LAC","LAD","LAG","LAM","LAP","LAR","LAS","LAT","LAV","LAW","LAX","LAY","LEA","LED","LEE","LEG","LEI","LEK",
"LES","LET","LEU","LEV","LEX","LEY","LIB","LID","LIE","LIN","LIP","LIS","LIT","LOG","LOO","LOP","LOT","LOW","LOX",
"LUG","LUV","LUX","LYE","MAC","MAD","MAE","MAG","MAN","MAP","MAR","MAS","MAT","MAW","MAX","MAY","MED","MEG","MEL",
"MEM","MEN","MET","MEW","MHO","MIC","MID","MIG","MIL","MIM","MIR","MIS","MIX","MOA","MOB","MOC","MOD","MOG","MOI",
"MOL","MOM","MON","MOO","MOP","MOR","MOS","MOT","MOW","MUD","MUG","MUM","MUN","MUS","MUT","NAB","NAE","NAG","NAH",
"NAM","NAN","NAP","NAW","NAY","NEE","NET","NEW","NIB","NIL","NIM","NIP","NIT","NIX","NOB","NOD","NOG","NOM","NOR",
"NOS","NOT","NOW","NTH","NUB","NUN","NUS","NUT","OAF","OAK","OAR","OAT","OBE","OBI","OCA","ODD","ODE","ODS","OFF",
"OFT","OHM","OHO","OHS","OIK","OIL","OKA","OKE","OLD","OLE","OMS","ONE","ONO","ONS","OOH","OOT","OPE","OPS","OPT",
"ORA","ORB","ORC","ORE","ORS","ORT","OSE","OUD","OUR","OUT","OVA","OWE","OWL","OWN","OXO","OXY","PAD","PAH","PAL",
"PAM","PAN","PAP","PAR","PAS","PAT","PAW","PAX","PAY","PEA","PEC","PED","PEE","PEG","PEH","PEN","PEP","PER","PES",
"PET","PEW","PHI","PIE","PIG","PIN","PIP","PIS","PIT","PIU","PIX","PLY","POD","POI","POL","POM","POP","POT","POW",
"POX","PRE","PRO","PRY","PSI","PUB","PUG","PUL","PUN","PUP","PUR","PUS","PUT","QAT","QUA","RAD","RAG","RAH","RAI",
"RAJ","RAM","RAN","RAP","RAS","RAT","RAW","RAX","RAY","REB","REC","RED","REE","REF","REG","REI","REM","REP","RES",
"RET","REV","REX","RHO","RIA","RIB","RID","RIF","RIG","RIM","RIN","RIP","ROB","ROC","ROD","ROE","ROM","ROT","ROW",
"RUB","RUE","RUG","RUM","RUN","RUT","RYA","RYE","SAB","SAC","SAD","SAG","SAL","SAP","SAT","SAU","SAW","SAX","SAY",
"SEA","SEC","SEE","SEG","SEL","SEN","SER","SET","SEW","SHA","SHE","SHH","SHY","SIB","SIC","SIM","SIN","SIP","SIR",
"SIS","SIT","SIX","SKA","SKI","SKY","SLY","SOB","SOD","SOL","SOM","SON","SOP","SOS","SOT","SOU","SOW","SOX","SOY",
"SPA","SPY","STY","SUB","SUE","SUM","SUN","SUP","SUQ","TAB","TAD","TAG","TAJ","TAM","TAN","TAO","TAP","TAR","TAS",
"TAT","TAU","TAV","TAW","TAX","TEA","TED","TEE","TEG","TEN","THE","THO","THY","TIC","TIE","TIN","TIP","TIS","TIT",
"TOD","TOE","TOG","TOM","TON","TOO","TOP","TOR","TOT","TOW","TOY","TRY","TSK","TUB","TUG","TUI","TUN","TUP","TUT",
"TUX","TWA","TWO","TYE","UDO","UGH","UKE","ULU","UMM","UMP","UNI","UNS","UPO","UPS","URB","URD","URN","URP","USE",
"UTA","UTE","UTS","VAC","VAN","VAR","VAS","VAT","VAU","VAV","VAW","VEE","VEG","VET","VEX","VIA","VID","VIE","VIG",
"VIM","VIS","VOW","VOX","VUG","WAB","WAD","WAG","WAN","WAP","WAR","WAS","WAT","WAW","WAX","WAY","WEB","WED","WEE",
"WEN","WET","WHA","WHO","WHY","WIG","WIN","WIS","WIT","WIZ","WOE","WOG","WOK","WON","WOO","WOP","WOS","WOT","WOW",
"YAH","YAK","YAM","YAP","YAW","YAY","YEA","YEH","YEN","YEP","YES","YET","YEW","YID","YIN","YIP","YOB","YOD","YOK",
"YOM","YON","YOU","YOW","YUK","YUM","YUP","ZAG","ZAP","ZAX","ZED","ZEE","ZEK","ZEN","ZEP","ZIG","ZIN","ZIP","ZIT",
"ZOA","ZOO",

// 4-letter additions - focus on missing ones
"ABET","ABUT","ACES","ACTS","ADDS","AFAR","AGES","AIDS","AIMS","AIRS","AIRY","ALES","ALLY","ALMS","AMID","AMPS",
"ANKH","ANTS","APES","APPS","AREA","ARIA","ARID","ARTS","ARTY","ASKS","ATOP","AUTO","AVID","AXIS","AXLE",
"BABY","BACK","BADE","BAGS","BAIL","BAIT","BAKE","BALD","BALE","BALK","BALM","BAND","BANE","BANG","BANK","BANS",
"BARD","BARE","BARK","BARN","BARS","BASE","BASH","BASK","BASS","BAST","BATH","BATS","BAWL","BAYS","BEAD","BEAK",
"BEAM","BEAN","BEAR","BEAT","BECK","BEDS","BEEF","BEEN","BEEP","BEER","BEES","BELL","BELT","BEND","BENT","BERG",
"BERM","BEST","BETA","BETS","BIAS","BIDE","BIDS","BIKE","BILE","BILL","BIND","BIRD","BITE","BITS","BLAH","BLED",
"BLEW","BLOB","BLOC","BLOG","BLOT","BLOW","BLUE","BLUR","BOAR","BOAT","BOBS","BODE","BODY","BOGS","BOIL","BOLD",
"BOLT","BOMB","BOND","BONE","BONG","BONK","BOOB","BOOK","BOOM","BOON","BOOR","BOOT","BORE","BORN","BOSS","BOTH",
"BOUT","BOWL","BOWS","BOYS","BRAG","BRAN","BRAT","BRED","BREW","BRIG","BRIM","BROW","BUCK","BUDS","BUFF","BUGS",
"BULB","BULK","BULL","BUMP","BUMS","BUNG","BUNK","BUNS","BUOY","BURN","BURP","BURR","BURY","BUSH","BUSY","BUTT",
"BUZZ","BYTE","CAFE","CAGE","CAKE","CALF","CALL","CALM","CAME","CAMP","CANE","CAPE","CAPS","CARD","CARE","CARP",
"CARS","CART","CASE","CASH","CASK","CAST","CATS","CAVE","CELL","CHAD","CHAP","CHAR","CHAT","CHEF","CHEW","CHIN",
"CHIP","CHIT","CHOP","CHOW","CHUB","CHUM","CITE","CITY","CLAD","CLAM","CLAN","CLAP","CLAW","CLAY","CLEF","CLIP",
"CLOG","CLOP","CLOT","CLUB","CLUE","COAL","COAT","COCK","CODA","CODE","CODS","COHO","COIL","COIN","COKE","COLA",
"COLD","COLT","COMA","COMB","COME","CONE","COOK","COOL","COOP","COPE","COPS","COPY","CORD","CORE","CORK","CORN",
"COST","COSY","COUP","COVE","COWS","COZY","CRAB","CRAM","CRAP","CRAW","CREW","CRIB","CROP","CROW","CRUD","CUBE",
"CUBS","CUED","CUES","CUFF","CULT","CUPS","CURB","CURD","CURE","CURL","CURT","CUSP","CUTE","CUTS","CZAR",
"DABS","DACE","DADO","DADS","DAFT","DALE","DAME","DAMN","DAMP","DAMS","DANK","DARE","DARK","DARN","DART","DASH",
"DATA","DATE","DAUB","DAWN","DAYS","DAZE","DEAD","DEAF","DEAL","DEAN","DEAR","DEBT","DECK","DEED","DEEM","DEEP",
"DEER","DEFT","DEFY","DELL","DEMO","DENS","DENT","DENY","DESK","DEWY","DIAL","DICE","DICK","DIED","DIES","DIET",
"DIGS","DILL","DIME","DIMS","DINE","DING","DINT","DIPS","DIRE","DIRK","DIRT","DISC","DISH","DISK","DISS","DIVE",
"DOCK","DODO","DOER","DOES","DOJO","DOLE","DOLL","DOLT","DOME","DONE","DOOM","DOOR","DOPE","DORK","DORM","DORY",
"DOSE","DOTE","DOTH","DOTS","DOUR","DOVE","DOWN","DOZE","DOZY","DRAB","DRAG","DRAM","DRAW","DRAY","DREW","DRIP",
"DROP","DRUB","DRUG","DRUM","DUAL","DUBS","DUCE","DUCK","DUCT","DUDE","DUDS","DUEL","DUFF","DUKE","DULL","DULY",
"DUMB","DUMP","DUNE","DUNG","DUNK","DUPE","DUSK","DUST","DUTY","DYED","DYER",
"EACH","EARL","EARN","EARS","EASE","EAST","EASY","EATS","EAVE","EDDY","EDGE","EDGY","EDIT","EELS","EGGS","ELSE",
"EMIT","EMUS","ENDS","ENVY","EPIC","ETCH","EURO","EVEN","EVER","EVIL","EWER","EXAM","EXEC","EXES","EXIT","EXPO",
"EYED","EYES",

// Completely new 4-letter words not yet in set
"ANKH","ARIA","ARTY","AUTO","AWRY","AXLE","BABY","BECK","BERG","BIDE","BIDS","BLEW","BODE","BRAT","BUSH",
"BYTE","CAFE","CHAR","CHIT","CHUB","CLEF","CLOP","CODA","COMA","COOP","COPS","CRAW","CRIB","CZAR","DADO",
"DOER","DUAL","DUCE","DUCT","EAVE","EDDY","EDGY","EURO","EXEC","EXPO","FARO","FAZE","FESS","FIAT","FIEF",
"FLAY","FLUB","FOCI","FOGY","FOXY","FRAY","FRET","FUNK","GAIT","GALA","GASP","GAWK","GERM","GLEE","GOAD",
"GONG","GOOF","GORY","GOSH","GOUT","GOWN","GRAD","GREY","GROG","GURU","HALO","HANK","HASP","HEFT","HICK",
"HIVE","HOAX","HONK","HOOF","HOOT","HULK","HUSK","HYPE","IBIS","IDOL","IFFY","IRIS","ITCH","JAMB","JAVA",
"JINX","JIVE","JOCK","JOWL","JUDO","JUNE","KALE","KHAN","KILN","KINK","LAUD","LAVA","LAZY","LEVY","LISP",
"LOBE","LOCO","LOGE","LOGO","LOIN","LOON","LOOT","LORN","LUGE","LYNX","LYRE","MAGI","MAIM","MAMA","MARS",
"MATH","MAUL","MEEK","MEGA","MEOW","METE","MINI","MINK","MINX","MOJO","MONK","MOOT","MURK","MUTT","NARC",
"NEON","NERD","NEWT","NICK","NOIR","NOPE","NOSY","NULL","OBIT","OGLE","OKRA","ONUS","ORCA","OUCH","OXEN",
"PALL","PANG","PANT","PAPA","PARE","PAWN","PESO","PIED","PING","PISS","PLAT","PLED","POKY","POLO","PONY",
"POOH","POOP","POOR","POSH","POSY","POUT","PREP","PRIG","PRIM","PROM","PUCK","PULL","PUNK","PURR","PUTT",
"QUAD","RACY","RAZE","REDO","REEK","REND","REPO","RICK","RIFE","RIME","RINK","RITE","ROOD","ROMP","ROTE",
"ROUT","RUED","RUES","RUFF","RUNE","RUNT","RUSE","SARI","SASS","SCAD","SCAM","SEEP","SEER","SEMI","SERF",
"SEWN","SHAG","SHAM","SHIV","SHUN","SILO","SINE","SING","SINK","SKAT","SKEW","SKID","SKIN","SKIP","SKIT",
"SLAW","SLAY","SLOG","SLUG","SMUG","SNIT","SOLO","SOOT","SPAS","SPAT","SPEW","SPRY","SPUN","SUBS","SUDS",
"SUMO","SWAB","SWAT","SWAY","TACO","TAMP","TANG","TAXI","TEAK","TEAL","TEAT","TECH","TEEM","TEEN","TERN",
"THAW","TING","TINT","TITS","TOFU","TOGA","TOGS","TOME","TONG","TONS","TORT","TOTE","TOUT","TRAM","TROD",
"TSAR","TUBA","TUFF","TURD","TUTU","TWIG","TYPO","VANE","VANS","VEER","VEND","VIAL","VIBE","VICE","VIED",
"VIES","VILE","VISE","VOLE","WADE","WANE","WARE","WARS","WELT","WEPT","WHET","WHEY","WHIR","WICK","WILT",
"WILY","WINS","WITS","WOES","WOMB","WOOF","WORM","WRAP","WUSS","YACK","YANK","YELP","YOGA","YOKE","YOLK",
"YOWL","YURT","ZEST","ZING",

// New 5-letter words not yet in set
"ABASH","ABYSS","ACORN","ADAGE","ADDED","ADDER","ADEPT","ADMIN","ADOBE","ADORE","ADORN","AEGIS","AFOOT","AGAPE",
"AGLOW","AIDED","AIDER","ALDER","ALGAE","ALIBI","ALLAY","ALLOT","ALLOY","ALOFT","ALOOF","ALOUD","ALPHA","AMASS",
"AMBER","AMBLE","AMEND","AMISS","AMITY","AMPLY","AMUSE","ANGST","ANIME","ANNEX","ANNOY","ANTIC","ANVIL","APHID",
"APRON","APTLY","ARBOR","AROMA","AROSE","ARROW","ARSON","ATONE","AUDIT","AUNTS","AVAIL","AVERT","AVIAN","AWOKE",
"AXIOM","AZURE","BABEL","BACON","BAGEL","BAGGY","BAKED","BAKER","BALMY","BANAL","BANJO","BARGE","BARON","BATCH",
"BATHE","BATON","BAYOU","BEADY","BEARD","BELLY","BERTH","BESET","BILGE","BINGE","BIRCH","BLAND","BLARE","BLEAK",
"BLEAT","BLIMP","BLINK","BLITZ","BLOAT","BLOKE","BLOND","BLOOD","BLUES","BLUFF","BLUSH","BOGEY","BOGGY","BOGUS",
"BONED","BONER","BOOST","BOOTY","BOOZE","BOOZY","BORNE","BOSOM","BOSSY","BOTCH","BOUGH","BOXER","BRACE","BRAID",
"BRAKE","BRASH","BRASS","BRAWL","BRAWN","BRIBE","BRINK","BRINY","BRISK","BROIL","BROOD","BROTH","BRUNT","BRUTE",
"BUDDY","BUGGY","BUGLE","BULGE","BULKY","BULLY","BUNNY","BURLY","BURNT","BYLAW",

// 6-letter additions - focus on brand new ones
"ACTING","ADHERE","ARREST","BABOON","BADGER","BAFFLE","BANGLE","BANTER","BARLEY","BATTEN","BATTER","BEAGLE","BEATEN",
"BEAVER","BEDLAM","BEHALF","BEHOLD","BELIEF","BENIGN","BEWARE","BIASED","BICEPS","BICKER","BIGWIG","BIKINI","BISECT",
"BITTEN","BLAZER","BLEACH","BLONDE","BLOODY","BLOTCH","BOBBIN","BODILY","BOILED","BONBON","BOOGER","BOOGIE","BOOKIE",
"BOTANY","BOTHER","BOUNCY","BOUNTY","BOVINE","BOWLER","BOXING","BRANDY","BREACH","BREEZY","BRIDLE","BROOCH","BRUNCH",
"BUCKLE","BUMBLE","BUMPER","BUNGLE","BUNGEE","BUNKER","BURROW","BUYOUT",
"CACKLE","CAJOLE","CANARY","CANCEL","CANCER","CANDID","CANINE","CANNON","CANOPY","CARING","CARROT","CARTON","CAVITY",
"CELLAR","CENSOR","CHASER","CHATTY","CHEESY","CHEEKY","CHESTY","CHROME","CHUNKY","CINDER","CINEMA","CIRCUS","CLASSY",
"CLAUSE","CLICHE","CLIMAX","CLIQUE","CLOTHE","CLOUDY","CLUMSY","CLUTCH","COARSE","COBALT","COBBLE","COBWEB","COCOON",
"CODDLE","COFFER","COFFIN","COMELY","CONVEX","CONVEY","COOLER","CORDON","CORONA","CORPSE","CORRAL","COSMIC","COUPON",
"COWARD","CRABBY","CRAFTY","CRANKY","CRATER","CRAVEN","CRAYON","CREAKY","CREAMY","CREEPY","CRISPY","CRUMMY","CRUSTY",
"CUDDLE","CUDDLY","CURFEW","CYBORG",

// 7-letter additions
"ABANDON","ABYSMAL","ACCLAIM","ACIDITY","AFFABLE","AIRSHIP","AIRPORT","ALCHEMY","ALLEGRO","AMNESIA","ANALYZE","ANARCHY",
"ANDROID","ANGELIC","ARCHAIC","ARCHIVE","ARDUOUS","ARTISAN","ARTWORK","AUDIBLE","AUTOPSY","AWESOME","AWKWARD",
"BABYSIT","BACKLOG","BAILOUT","BALCONY","BANDAGE","BANKING","BANQUET","BAPTISM","BARISTA","BASHFUL","BEDROCK","BESPOKE",
"BETWEEN","BIPLANE","BIZARRE","BLEMISH","BLESSED","BLINKER","BLOATED","BLOGGER","BLOTCHY","BOATING","BOLSTER","BOMBARD",
"BONFIRE","BOOLEAN","BOOSTER","BOROUGH","BOYCOTT","BREAKUP","BRIEFER","BRIGADE","BRISTLE","BROADLY","BROILER","BUCKLER",
"BULLION","BUMPKIN","BUNGLER","BURGLAR","BURNISH",
"CARAMEL","CARRION","CASHIER","CERTIFY","CHARGER","CHARITY","CHOWDER","CLAMBER","CLEANER","CLIPPER","CLOSEST","CLOSURE",
"CLUTTER","COEXIST","COLDEST","COLLAGE","COMMEND","COMPACT","COMPASS","COMPOST","CONCAVE","CONCEDE","CONGEST","COOLEST",
"COPILOT","CORRODE","CORRUPT","COVERED","CRAFTER","CRAMPED","CRUELTY","CRUISER","CRUMBLE","CUNNING","CUPCAKE","CURATOR",
"CURIOUS","CURTAIL","CUSHION","CUSTARD",
"DAMNING","DANCING","DASHING","DAYLONG","DEBATER","DEEPEST","DENTIST","DISCERN","DISDAIN","DISRUPT","DISSENT","DISTILL",
"DIVIDED","DIVORCE","DOUBLES","DRINKER","DROPLET","DUBIOUS","DUNGEON","DYNASTY",
"EAGERLY","ECLIPSE","ECONOMY","ELECTED","ELUSIVE","EMANATE","EMBASSY","EMERALD","EMPRESS","ENABLED","ENDEMIC","ENLARGE",
"ENLIVEN","ENRAGED","ENSNARE","EPITOME","ERRATIC","ETERNAL","EVENING","EXACTLY","EXCITED","EXPANSE","EXTINCT","EYELASH",

// More unique words by going through missing common ones
"AMID","BASK","BECK","BERG","BERM","BIDE","BIDS","BLEW","BODE","BOWS","BRAT","BUSH","BYTE","CHAR","CHIT","CHUB",
"CLEF","CLOP","CODA","COMA","COOP","COPS","CRAW","CRIB","CZAR","DADO","DOER","DUCE","DUCT","EAVE","EDDY","EDGY",
"EURO","EXEC","EXPO","FARO","FAZE","FESS","FIAT","FIEF","FLAY","FLUB","FOCI","FOGY","FOXY","FRAY","FRET","FUNK",
"GAIT","GALA","GASP","GAWK","GERM","GLEE","GOAD","GONG","GOOF","GORY","GOSH","GOUT","GOWN","GRAD","GREY","GROG",

// More truly new 4-letter words
"ACAI","ARGH","BLAB","BLED","BRRR","BURB","CARP","CHOW","CLAM","CLAP","CRAW","CZAR","DANG","DOJO","DORK","DOTE",
"EDGY","EKED","FENG","FLAK","GAIT","GLAM","GRIT","GROK","GYRO","HEMP","HOBO","HUNH","JEEP","KELP","MEGA","MEOW",
"NAAN","NADA","NAFF","NEAP","OGLE","OHMS","OKRA","OLEO","OREO","OUCH","PAPA","PAWN","PERP","PIER","PLOP","PREX",
"PRIG","PURR","RAZZ","RIFF","ROOK","RUNE","SCAB","SHIV","SKID","SLAG","SMOG","SNIT","SPUD","SWAG","TANG","THAW",
"TOFU","TOGA","TYPO","VAMP","VIBE","WAIF","WUSS","YURT","ZANY","ZING","AAHS","AHEM","AMMO","ANTS","AXED","BARD",
"BASK","BIAS","BOAR","BODE","BRED","CHOW","COGS","COMA","COOP","DACE","DAIS","DAWG","DECO","DELI","DODO","DOJO",
"DRUB","DYER","EAVE","ELKS","EMUS","EXEC","EXPO","FETA","FIAT","FIEF","FLAN","FLAX","FLAY","FLUB","FOCI","FOGY",
"FOWL","FOXY","FRAY","FRET","FROG","FUNK","FURY","GALE","GALL","GASH","GASP","GAWK","GERM","GLIB","GOAD","GOBS",
"GONG","GOOF","GORY","GOSH","GOUT","GRAD","GREY","GROG","GRUB","GULL","GUMS","GUNK","GURU","HALO","HASP","HEFT",
"HICK","HIVE","HOAX","HONK","HOOF","HOOT","HULK","HUSK","HYPE","IBIS","IDOL","IFFY","IRIS","ITCH","JADE","JAKE",
"JAMB","JAVA","JINX","JIVE","JOCK","JOSH","JOWL","JUDO","KALE","KHAN","KILN","KINK","KITE","LAUD","LAVA","LEVY",
"LISP","LOBE","LOCO","LOGE","LOGO","LOIN","LOON","LOOT","LORN","LUGE","LYNX","LYRE","MAGI","MAIM","MAMA","MARS",
"MATH","MAUL","MEEK","MEGA","METE","MINI","MINK","MINX","MOJO","MONK","MOOT","MURK","MUTT","NARC","NEON","NEWT",
"NICK","NOIR","NOPE","NOSY","NULL","OBIT","OGLE","OKRA","ONUS","ORCA","OXEN","PALL","PANG","PANT","PAPA","PARE",
"PESO","PIED","PING","PLAT","PLED","POKY","POLO","PONY","POOH","POOP","POSH","POSY","POUT","PREP","PRIG","PRIM",
"PROM","PUCK","PULL","PUNK","PURR","PUTT","QUAD","RACY","RAZE","REDO","REEK","REND","REPO","RICK","RIFE","RIME",
"RINK","RITE","ROOD","ROTE","ROUT","RUED","RUES","RUFF","RUNE","RUNT","RUSE","SARI","SASS","SCAD","SCAM","SEEP",
"SEER","SEMI","SERF","SEWN","SHAG","SHAM","SHIV","SHUN","SILO","SINE","SKAT","SKEW","SLAW","SLAY","SLOG","SMUG",
"SNIT","SOLO","SOOT","SPAS","SPAT","SPEW","SPRY","SPUN","SUDS","SUMO","SWAB","SWAT","SWAY","TACO","TAMP","TAXI",
"TEAK","TEAL","TEAT","TECH","TEEM","TEEN","TERN","THAW","TING","TINT","TOFU","TOGA","TOGS","TOME","TONG","TONS",
"TORT","TOTE","TOUT","TRAM","TSAR","TUBA","TUFF","TURD","TUTU","TWIG","TYPO","VANE","VANS","VEER","VEND","VIAL",
"VIBE","VIED","VIES","VILE","VISE","VOLE","WANE","WARE","WELT","WEPT","WHET","WHEY","WHIR","WILY","WOES","WOMB",
"WOOF","WRAP","WUSS","YACK","YANK","YELP","YOGA","YOKE","YOLK","YOWL","YURT","ZEST","ZING",

// Totally new words - common English words that might not be included
"ALOE","AMMO","APPS","AVID","BARB","BASH","BEAM","BEET","BERG","BERM","BETS","BLIP","BLOB","BOLT","BOMB","BONG",
"BOON","BOOR","BOUT","BRAN","BREW","BRIG","BRIM","BUCK","BULB","BULK","BUMP","BUNG","BUNK","BUOY","BURP","BURR",
"BURY","BUZZ","CAFE","CAPE","CARP","CASK","CAVE","CHIP","CHOW","CHUM","CLAM","CLAP","CLAW","CLAY","CLIP","CLOG",
"COAL","CODA","COIL","COLA","COLT","COMB","CONE","COOL","COPE","COPY","CORK","COST","COSY","COUP","COVE","CRAB",
"CRAM","CRAP","CREW","CROW","CUBE","CULT","CURB","CURE","CURL","CUTE","DALE","DAMP","DARE","DARK","DARN","DART",
"DASH","DATA","DATE","DAWN","DEAF","DEAL","DEEP","DEMO","DENY","DESK","DIAL","DICE","DINE","DIRE","DIRT","DIVE",
"DOCK","DOME","DOSE","DOVE","DOWN","DOZE","DRAG","DRAW","DRIP","DROP","DRUG","DRUM","DUEL","DUFF","DUKE","DULL",
"DUMP","DUNG","DUNK","DUPE","DUSK","DUST","DUTY","EARN","EASE","EAST","EASY","EDGE","EDIT","FACE","FACT","FADE",
"FAIL","FAIR","FAKE","FALL","FAME","FARM","FAST","FATE","FEAR","FEAT","FEED","FEEL","FELL","FELT","FILE","FILL",
"FILM","FIND","FINE","FIRE","FIRM","FISH","FIST","FIVE","FLAG","FLAP","FLAT","FLAW","FLEA","FLED","FLEE","FLEW",
"FLIP","FLIT","FLOG","FLOP","FLOW","FOAM","FOIL","FOLD","FOLK","FOND","FONT","FOOD","FOOL","FOOT","FORD","FORK",
"FORM","FORT","FOUL","FOUR","FREE","FROM","FUEL","FULL","FUND","GAIN","GAME","GANG","GAPE","GARB","GATE","GAVE",
"GAZE","GEAR","GEMS","GENE","GIFT","GIRL","GIST","GIVE","GLAD","GLEN","GLOW","GLUE","GLUM","GLUT","GNAT","GNAW",
"GOAL","GOAT","GOLD","GOLF","GONE","GOOD","GORE","GRAB","GRAM","GRAY","GREW","GRID","GRIM","GRIN","GRIP","GRIT",
"GROW","GULF","GULP","GUST","GUTS","GUYS","HACK","HAIL","HAIR","HALE","HALF","HALL","HALT","HAND","HANG","HARE",
"HARM","HARP","HASH","HATE","HAUL","HAVE","HAWK","HAZE","HAZY","HEAD","HEAL","HEAP","HEAR","HEAT","HEED","HEEL",
"HELD","HELM","HELP","HERB","HERE","HERO","HIDE","HIGH","HIKE","HILL","HILT","HIND","HINT","HIRE","HOLD","HOLE",
"HOLY","HOME","HONE","HOOD","HOOK","HOOP","HOPE","HORN","HOSE","HOST","HOUR","HOWL","HUGE","HULL","HUMP","HUNG",
"HUNK","HUNT","HURL","HURT","HUSH","HYMN","ICON","IDEA","IDLE","INCH","INTO","IRON","ISLE","ITEM","JACK","JAIL",
"JAZZ","JEAN","JEER","JEST","JOKE","JOLT","JUMP","JUNK","JURY","JUST","KEEN","KEEP","KEPT","KICK","KILL","KIND",
"KING","KISS","KNEE","KNEW","KNIT","KNOB","KNOT","KNOW","LACE","LACK","LAID","LAIR","LAKE","LAME","LAMP","LAND",
"LANE","LARD","LASH","LASS","LAST","LATE","LAWN","LEAD","LEAF","LEAK","LEAN","LEAP","LEFT","LEND","LENS","LENT",
"LESS","LIAR","LICK","LIFE","LIFT","LIKE","LILY","LIMB","LIME","LIMP","LINE","LINK","LINT","LION","LIST","LIVE",
"LOAD","LOAF","LOAM","LOAN","LOCK","LODE","LOFT","LONE","LONG","LOOK","LOOM","LOOP","LORD","LORE","LOSE","LOSS",
"LOST","LOUD","LOVE","LUCK","LULL","LUMP","LUNG","LURE","LURK","LUSH","LUST","MACE","MADE","MAID","MAIL","MAIN",
"MAKE","MALE","MALL","MALT","MANE","MANY","MARE","MARK","MASH","MASK","MASS","MAST","MATE","MAZE","MEAD","MEAL",
"MEAN","MEAT","MEET","MELD","MELT","MEMO","MEND","MENU","MERE","MESH","MESS","MILD","MILE","MILK","MILL","MIME",
"MIND","MINE","MINT","MIRE","MISS","MIST","MITE","MITT","MOAN","MOAT","MOCK","MODE","MOLD","MOLE","MOLT","MOOD",
"MOON","MOOR","MOPE","MORE","MOSS","MOST","MOTH","MOVE","MUCH","MUCK","MUFF","MULE","MULL","MUSE","MUSH","MUSK",
"MUST","MUTE","MYTH","NAIL","NAME","NAPE","NAVY","NEAR","NEAT","NECK","NEED","NEST","NEXT","NICE","NINE","NODE",
"NONE","NOOK","NOON","NORM","NOSE","NOTE","NOUN","NUDE","NUMB","OATH","OBEY","ODDS","ODOR","OGRE","OINK","OKAY",
"OMEN","OMIT","ONCE","ONLY","ONTO","OOZE","OPAL","OPEN","ORAL","OVEN","OVER","OWED","PACE","PACK","PACT","PAGE",
"PAID","PAIL","PAIN","PAIR","PALE","PALM","PANE","PARK","PART","PASS","PAST","PATH","PAVE","PEAK","PEAL","PEAR",
"PEAT","PECK","PEEL","PEEK","PEER","PELT","PERK","PEST","PICK","PIKE","PILE","PILL","PINE","PINK","PINT","PIPE",
"PLAN","PLAY","PLEA","PLOD","PLOT","PLOW","PLOY","PLUG","PLUM","PLUS","POEM","POET","POKE","POLE","POLL","POMP",
"POND","POOL","POPE","PORE","PORK","PORT","POSE","POST","POUR","PRAY","PREY","PROD","PROP","PROW","PULP","PUMP",
"PURE","PUSH","QUAY","QUIZ","RACE","RACK","RAFT","RAGE","RAID","RAIL","RAIN","RAKE","RAMP","RANG","RANK","RANT",
"RARE","RASH","RASP","RATE","RAVE","READ","REAL","REAM","REAP","REAR","REED","REEF","REEL","REIN","RELY","RENT",
"REST","RICH","RIDE","RIFT","RILE","RILL","RIND","RING","RIOT","RISE","RISK","ROAD","ROAM","ROAR","ROBE","ROCK",
"RODE","ROLE","ROLL","ROOF","ROOM","ROOT","ROPE","ROSE","ROSY","ROVE","RUDE","RUIN","RULE","RUMP","RUNG","RUSH",
"RUST","SACK","SAFE","SAGE","SAID","SAIL","SAKE","SALE","SALT","SAME","SAND","SANE","SANG","SANK","SASH","SAVE",
"SEAL","SEAM","SEAR","SEAT","SECT","SEED","SEEK","SEEM","SEEN","SELF","SELL","SEND","SENT","SHED","SHIN","SHIP",
"SHOE","SHOO","SHOP","SHOT","SHOW","SHUT","SICK","SIDE","SIFT","SIGH","SIGN","SILK","SILL","SILT","SIRE","SITE",
"SIZE","SLAB","SLAM","SLAP","SLAT","SLED","SLEW","SLID","SLIM","SLIT","SLOB","SLOP","SLOT","SLOW","SLUM","SLUR",
"SMOG","SNAP","SNAG","SNIP","SNOB","SNOT","SNOW","SNUB","SNUG","SOAK","SOAP","SOAR","SOCK","SODA","SOFA","SOFT",
"SOIL","SOLD","SOLE","SOME","SONG","SOON","SORE","SORT","SOUL","SOUR","SPAN","SPAR","SPEC","SPED","SPIN","SPIT",
"SPOT","SPUR","STAB","STAG","STAR","STAY","STEM","STEP","STEW","STIR","STOP","STOW","STUB","STUD","STUN","SUCH",
"SUCK","SUIT","SULK","SUMP","SUNG","SUNK","SURE","SURF","SWAN","SWAP","SWIM","SWUM","TACK","TACT","TAIL","TAKE",
"TALE","TALK","TALL","TAME","TANK","TAPE","TART","TASK","TEAM","TEAR","TELL","TEMP","TEND","TENT","TERM","TEST",
"TEXT","THAN","THAT","THEM","THEN","THEY","THIN","THIS","THUD","THUG","THUS","TICK","TIDE","TIDY","TIED","TIER",
"TIFF","TILE","TILL","TILT","TIME","TINE","TINY","TIRE","TOAD","TOIL","TOLD","TOLL","TOMB","TONE","TOOK","TOOL",
"TOPS","TORE","TORN","TOSS","TOUR","TOWN","TRAP","TRAY","TREE","TREK","TRIM","TRIO","TRIP","TROT","TRUE","TUBE",
"TUCK","TUFT","TUNA","TUNE","TURF","TURN","TUSK","TWIN","TYPE","UGLY","UNDO","UNIT","UNTO","UPON","URGE","USED",
"USER","VAIN","VALE","VARY","VASE","VAST","VEAL","VEIL","VEIN","VENT","VERB","VERY","VEST","VIEW","VINE","VISA",
"VOID","VOLT","VOTE","WADE","WAGE","WAIL","WAIT","WAKE","WALK","WALL","WAND","WANT","WARD","WARM","WARN","WARP",
"WART","WARY","WASH","WASP","WAVE","WAVY","WAXY","WEAK","WEAN","WEAR","WEED","WEEK","WEEP","WELD","WELL","WENT",
"WERE","WEST","WHAT","WHEN","WHIM","WHIP","WHOM","WIDE","WIFE","WILD","WILL","WIMP","WIND","WINE","WING","WINK",
"WIPE","WIRE","WISE","WISH","WISP","WITH","WOKE","WOLF","WOOD","WOOL","WORD","WORE","WORK","WORN","WOVE","WREN",
"WRIT","YARD","YARN","YEAR","YELL","YORE","YOUR","ZEAL","ZERO","ZINC","ZONE","ZOOM"
];

let added = 0;
for (const w of candidates) {
  const upper = w.toUpperCase().trim();
  if (upper.length >= 3 && upper.length <= 7 && /^[A-Z]+$/.test(upper)) {
    if (!existing.has(upper)) {
      existing.add(upper);
      added++;
    }
  }
}

console.log('New unique words added:', added);

const sorted = [...existing].sort();
let by3 = 0, by4 = 0, by5 = 0, by6 = 0, by7 = 0;
for (const w of sorted) {
  if (w.length === 3) by3++;
  else if (w.length === 4) by4++;
  else if (w.length === 5) by5++;
  else if (w.length === 6) by6++;
  else if (w.length === 7) by7++;
}
console.log('Total words:', sorted.length);
console.log('3-letter:', by3, '4-letter:', by4, '5-letter:', by5, '6-letter:', by6, '7-letter:', by7);

const wordData = sorted.join('\n');
const output = 'const WORD_DATA = `' + wordData + '`;' + exportSection;
fs.writeFileSync('src/data/wordList.ts', output);
console.log('File written successfully!');
